apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamodb-data
  labels:
    app: dynamodb
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
