apiVersion: v1
kind: Service
metadata:
  name: mailpit
  labels:
    app: mailpit
spec:
  selector:
    app: mailpit
  ports:
    - name: http
      protocol: TCP
      port: 8025
      targetPort: http
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: smtp
