{{ $outerContext := . }}
{{- range $kind, $valuesPerApp := .Values.apps }}
{{- with $outerContext }}
{{- if $valuesPerApp.enabled | default false }}
{{- template "sample-app.hpa" (list . $kind) }}
{{ end }}
{{- end }}
{{- end }}