---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-app.fullname" . }}-env
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
stringData:
  SAMPLE_DB_URI_MASTER: {{ .Values.appSettings.db.master.uri | toString | toYaml }}
  SAMPLE_DB_URI_MASTER_REPL: {{ .Values.appSettings.db.master.replUri | toString | toYaml }}
  SAMPLE_DB_URI_TMP: {{ .Values.appSettings.db.tmp.uri | toString | toYaml }}
  SAMPLE_APP_DASHBOARD_RECAPTCHA_SECRET_KEY: {{ .Values.appSettings.recaptcha.dashboard.secretKey | toString | toYaml }}
  {{- if .Values.appSettings.aws.overrides.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.appSettings.aws.overrides.accessKeyId | toString | toYaml }}
  {{- end }}
  {{- if .Values.appSettings.aws.overrides.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.appSettings.aws.overrides.secretAccessKey | toString | toYaml }}
  {{- end }}
{{- if (not (.Values.appSettings.environment | eq "production")) | and .Values.appSettings.populateDatabase }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-app.fullname" . }}-env-for-populate
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
stringData:
  SAMPLE_DB_TMP_URI: {{ .Values.appSettings.db.tmp.uri | toString | toYaml }}
{{- end }}